[package]
name = "bin-pr3"
version = "0.1.0"
authors = ["Mohamed <mek.mohamed.khamlichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello_exercism = "0.4.0"
pr3_exercism = {path ="../lib-pr3"}
